### ISSUE TITLE
Dodanie miejsc i zmiana ich Jsonów

### ISSUE THREAD

**Issue by Patryk-Zygmunt** [Patryk-Informatyk/Turism-Simulation#2]
https://github.com/Patryk-Informatyk/Turism-Simulation/wiki/place

**Comment by Patryk-Zygmunt** [comment]
Jakby jakieś problemy były  to może któś wyszukać tylko miejsca spisac placeId wysłać do mnie i ja te dane pobiore, a pozniej odeśle plik.json i ten ktoś go
 pozmienia

**Comment by grzepucz** [comment]
[placejson.zip](https://github.com/Patryk-Informatyk/Turism-Simulation/files/1610095/placejson.zip)
